lcgcmt_installarea=without_installarea
CMTPATH=/data2/kc2019/workfs/7.0.3:/data/lzuhep/sw/Boss/dist/7.0.3:/data/lzuhep/sw/Boss/gaudi/GAUDI_v23r9:/data/lzuhep/sw/Boss/LCGCMT/LCGCMT_65a
CMT_tag=$(tag)
CMTROOT=/data/lzuhep/sw/Boss/CMT/v1r25
CMT_root=/data/lzuhep/sw/Boss/CMT/v1r25
CMTVERSION=v1r25
CMT_offset=/data/lzuhep/sw/Boss
cmt_hardware_query_command=uname -m
cmt_hardware=`$(cmt_hardware_query_command)`
cmt_system_version_query_command=${CMTROOT}/mgr/cmt_linux_version.sh | ${CMTROOT}/mgr/cmt_filter_version.sh
cmt_system_version=`$(cmt_system_version_query_command)`
cmt_compiler_version_query_command=${CMTROOT}/mgr/cmt_gcc_version.sh | ${CMTROOT}/mgr/cmt_filter3_version.sh
cmt_compiler_version=`$(cmt_compiler_version_query_command)`
PATH=/data2/kc2019/workfs/7.0.3/InstallArea/share/bin:/data/lzuhep/sw/Boss/dist/7.0.3/InstallArea/share/bin:/data/lzuhep/sw/Boss/gaudi/GAUDI_v23r9/InstallArea/share/bin:/data/lzuhep/sw/Boss/LCGCMT/LCGCMT_65a/InstallArea/share/bin:/data2/kc2019/workfs/7.0.3/InstallArea/x86_64-slc6-gcc46-opt/scripts:/data/lzuhep/sw/Boss/dist/7.0.3/InstallArea/x86_64-slc6-gcc46-opt/scripts:/data/lzuhep/sw/Boss/gaudi/GAUDI_v23r9/InstallArea/x86_64-slc6-gcc46-opt/scripts:/data2/kc2019/workfs/7.0.3/InstallArea/${CMTCONFIG}/bin:/data/lzuhep/sw/Boss/dist/7.0.3/InstallArea/${CMTCONFIG}/bin:/data/lzuhep/sw/Boss/gaudi/GAUDI_v23r9/InstallArea/${CMTCONFIG}/bin:/data/lzuhep/sw/Boss//external/ROOT/5.34.09/x86_64-slc6-gcc46-opt/root/bin:/data/lzuhep/sw/Boss//external/xrootd/3.2.7/x86_64-slc6-gcc46-opt/bin:/data/lzuhep/sw/Boss//external/gccxml/0.9.0_20120309p2/x86_64-slc6-gcc46-opt/bin:/data/lzuhep/sw/Boss//external/tcmalloc/1.7p3/x86_64-slc6-gcc46-opt/bin:/data/lzuhep/sw/Boss//external/Python/2.7.3/x86_64-slc6-gcc46-opt/bin:/data/lzuhep/sw/Boss//external/gcc/4.6.3/x86_64-slc6/bin:/data/lzuhep/sw/Boss/CMT/v1r25/${CMTBIN}:/data/lzuhep/sw/Boss//external/pytools/1.8_python2.7/x86_64-slc6-gcc46-opt/bin:/data/lzuhep/sw/Boss//external/sqlite/3070900/x86_64-slc6-gcc46-opt/bin:/data/lzuhep/sw/Boss//external/mysql/5.5.14/x86_64-slc6-gcc46-opt/bin:/data/lzuhep/sw/Boss//external/XercesC/3.1.1p1/x86_64-slc6-gcc46-opt/bin:/data/lzuhep/sw/Boss//external/castor/2.1.13-6/x86_64-slc6-gcc46-opt/usr/bin:/data/lzuhep/sw/Boss/contrib/gcc46/bin:/usr/local/openmpi/bin:/usr/local/torque/bin:/usr/local/torque/sbin:/usr/local/bin:/bin:/usr/bin:/usr/sbin:/sbin:/data/lzuhep/sw/Boss//external/cernlib/2006a/x86_64-slc6-gcc46-opt/bin:/homekc2019/kc2019/bin
CLASSPATH=/data/lzuhep/sw/Boss/CMT/v1r25/java
debug_option=-g
cc=$(cc_name)
cdebugflags=$(coptimized_s)
cflags= -fmessage-length=0 -fPIC 
ccomp=$(cc) -c $(includes) $(cdebugflags) $(cflags) $(pp_cflags)
clink=$(cc) $(clinkflags) $(cdebugflags)
cdepflags=-MMD -MP -MF $*.d -MQ $@
vsCONFIG=Release
vsOptimize=2
ppcmd=-I
preproc=c++ -MD -c 
cpp=$(cpp_name)
cppdebugflags=$(cppoptimized_s)
cppflags= -fmessage-length=0    -Wall -Wextra  -pthread  -Wno-deprecated -D_GNU_SOURCE -pthread -pipe -ansi -pedantic -W -Wall -Wwrite-strings -Wpointer-arith -Woverloaded-virtual -Wno-long-long  -fPIC -march=x86-64 -mtune=x86-64 -pedantic-errors -O2
pp_cppflags=-D_GNU_SOURCE -DGAUDI_V20_COMPAT  -DBOOST_FILESYSTEM_VERSION=3 
cppcomp=$(cpp) -c $(cppdebugflags) $(cppflags) $(pp_cppflags) $(includes)
cpplinkflags=-Wl,-Bdynamic $(linkdebugflags) -ldl  -Wl,--no-undefined -Wl,--export-dynamic 
cpplink=$(cpp) $(cpplinkflags)
cppdepflags=-MMD -MP -MF $*.d -MQ $@
for=$(for_name)
fflags=-fmessage-length=0 -O2   -fPIC -pipe -fno-second-underscore -Wall -W -Wsurprising -fPIC 
fcomp=$(for) -c $(fincludes) $(fdebugflags) $(fflags) $(pp_fflags)
flink=$(for) $(flinkflags)
javacomp=javac -classpath $(src):$(CLASSPATH) 
javacopy=cp
jar=jar
X11_cflags=-I/usr/include
Xm_cflags=-I/usr/include
X_linkopts=-L/usr/X11R6/lib -lXm -lXt -lXext -lX11 -lm
lex=lex $(lexflags)
yaccflags= -l -d 
yacc=yacc $(yaccflags)
ar=ar cr
ranlib=ranlib
make_shlib=${CMTROOT}/mgr/cmt_make_shlib_common.sh extract
shlibsuffix=so
shlibbuilder=$(cpp_name) $(cmt_installarea_linkopts) 
shlibflags=-shared
symlink=symlink.sh
symunlink=/bin/rm -f 
library_install_command=python $(GaudiPolicy_root)/scripts/install.py -xCVS -x*~ -x*.stamp -x*.bak -x.* -x*.pyc -x*.pyo -s --log=./install.$(tag).history 
build_library_links=$(cmtexe) build library_links -tag=$(tags)
remove_library_links=$(cmtexe) remove library_links -tag=$(tags)
cmtexe=${CMTROOT}/${CMTBIN}/cmt.exe
build_prototype=$(cmtexe) build prototype
build_dependencies=$(cmtexe) -tag=$(tags) build dependencies
build_triggers=$(cmtexe) build triggers
format_dependencies=${CMTROOT}/mgr/cmt_format_deps.sh
implied_library_prefix=-l
SHELL=/bin/sh
q="
src=../src/
doc=../doc/
inc=../src/
mgr=../cmt/
application_suffix=.exe
library_prefix=lib
unlock_command=rm -rf 
lock_name=cmt
lock_suffix=.lock
lock_file=${lock_name}${lock_suffix}
svn_checkout_command=python ${CMTROOT}/mgr/cmt_svn_checkout.py 
gmake_hosts=lx1 rsplus lxtest as7 dxplus ax7 hp2 aleph hp1 hpplus papou1-fe atlas
make_hosts=virgo-control1 rio0a vmpc38a
everywhere=hosts
GUID_all={8BC9CEB8-8B4A-11D0-8D11-00A0C91BC955}
package_GUID={8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}
install_command=cp -R 
uninstall_command=python $(GaudiPolicy_root)/scripts/install.py -u --log=./install.$(tag).history 
cmt_installarea_command=python $(GaudiPolicy_root)/scripts/install.py -xCVS -x*~ -x*.stamp -x*.bak -x.* -x*.pyc -x*.pyo -s --log=./install.$(tag).history 
cmt_uninstallarea_command=/bin/rm -f 
cmt_install_area_command=$(symlink_command)
cmt_uninstall_area_command=$(uninstall_command)
cmt_install_action=$(CMTROOT)/mgr/cmt_install_action.sh
cmt_installdir_action=$(CMTROOT)/mgr/cmt_installdir_action.sh
cmt_uninstall_action=$(CMTROOT)/mgr/cmt_uninstall_action.sh
cmt_uninstalldir_action=$(CMTROOT)/mgr/cmt_uninstalldir_action.sh
mkdir=mkdir
cmt_installarea_prefix=InstallArea
CMT_PATH_remove_regexp=/[^/]*/
CMT_PATH_remove_share_regexp=/share/
NEWCMTCONFIG=x86_64-sl610-gcc463
McDecayModeSvc_tag=$(tag)
MCDECAYMODESVCROOT=/data2/kc2019/workfs/7.0.3/Analysis/McDecayModeSvc/McDecayModeSvc-00-00-01
McDecayModeSvc_root=/data2/kc2019/workfs/7.0.3/Analysis/McDecayModeSvc/McDecayModeSvc-00-00-01
MCDECAYMODESVCVERSION=McDecayModeSvc-00-00-01
McDecayModeSvc_cmtpath=/data2/kc2019/workfs/7.0.3
McDecayModeSvc_offset=Analysis
McDecayModeSvc_project=workfs
McDecayModeSvc_project_release=7.0.3
BesPolicy_tag=$(tag)
BESPOLICYROOT=/data/lzuhep/sw/Boss/dist/7.0.3/BesPolicy/BesPolicy-01-05-05
BesPolicy_root=/data/lzuhep/sw/Boss/dist/7.0.3/BesPolicy/BesPolicy-01-05-05
BESPOLICYVERSION=BesPolicy-01-05-05
BesPolicy_cmtpath=/data/lzuhep/sw/Boss/dist/7.0.3
BesPolicy_project=BOSS
BesPolicy_project_release=7.0.3
BesCxxPolicy_tag=$(tag)
BESCXXPOLICYROOT=/data/lzuhep/sw/Boss/dist/7.0.3/BesCxxPolicy/BesCxxPolicy-00-01-01
BesCxxPolicy_root=/data/lzuhep/sw/Boss/dist/7.0.3/BesCxxPolicy/BesCxxPolicy-00-01-01
BESCXXPOLICYVERSION=BesCxxPolicy-00-01-01
BesCxxPolicy_cmtpath=/data/lzuhep/sw/Boss/dist/7.0.3
BesCxxPolicy_project=BOSS
BesCxxPolicy_project_release=7.0.3
GaudiPolicy_tag=$(tag)
GAUDIPOLICYROOT=/data/lzuhep/sw/Boss/gaudi/GAUDI_v23r9/GaudiPolicy
GaudiPolicy_root=/data/lzuhep/sw/Boss/gaudi/GAUDI_v23r9/GaudiPolicy
GAUDIPOLICYVERSION=v12r7
GaudiPolicy_cmtpath=/data/lzuhep/sw/Boss/gaudi/GAUDI_v23r9
GaudiPolicy_project=GAUDI
GaudiPolicy_project_release=GAUDI_v23r9
LCG_Settings_tag=$(tag)
LCG_SETTINGSROOT=/data/lzuhep/sw/Boss/LCGCMT/LCGCMT_65a/LCG_Settings
LCG_Settings_root=/data/lzuhep/sw/Boss/LCGCMT/LCGCMT_65a/LCG_Settings
LCG_SETTINGSVERSION=v1
LCG_Settings_cmtpath=/data/lzuhep/sw/Boss/LCGCMT/LCGCMT_65a
LCG_Settings_project=LCGCMT
LCG_Settings_project_release=LCGCMT_65a
LCG_releases=${EXTERNALLIBDIR}/external
LCG_external=${EXTERNALLIBDIR}/external
unixdirname=lib64
gcc_config_version=4.6.3
gcc_native_version=$(gcc_config_version)
gcc_home=$(LCG_external)/gcc/$(gcc_native_version)/$(LCG_hostos)
clang_native_version=$(clang_config_version)
clang_home=$(LCG_external)/llvm/$(clang_native_version)/$(LCG_hostos)
icc_native_version=$(icc_config_version)
cc_name=lcg-gcc-$(gcc_config_version)
cpp_name=lcg-g++-$(gcc_config_version)
cpplinkname=$(cpp_name)
for_name=lcg-gfortran-$(gcc_config_version)
COMPILER_PATH=/data/lzuhep/sw/Boss//external/gcc/4.6.3/x86_64-slc6/lib/gcc/x86_64-unknown-linux-gnu/4.6.3
LD_LIBRARY_PATH=/lib:/data2/kc2019/workfs/7.0.3/InstallArea/${CMTCONFIG}/lib:/data/lzuhep/sw/Boss/dist/7.0.3/InstallArea/${CMTCONFIG}/lib:/data/lzuhep/sw/Boss/gaudi/GAUDI_v23r9/InstallArea/${CMTCONFIG}/lib:${STRING_DIR}/${CMTCONFIG}:${ALIST_DIR}/${CMTCONFIG}:/data/lzuhep/sw/Boss//external/HepPDT/2.06.01/x86_64-slc6-gcc46-opt/lib:/data/lzuhep/sw/Boss//external/HepMC/2.06.08/x86_64-slc6-gcc46-opt/lib:/data/lzuhep/sw/Boss//external/clhep/2.0.4.5/x86_64-slc6-gcc46-opt/lib:/data/lzuhep/sw/Boss//external/Boost/1.50.0_python2.7/x86_64-slc6-gcc46-opt/lib:/data/lzuhep/sw/Boss//external/ROOT/5.34.09/x86_64-slc6-gcc46-opt/root/lib:/data/lzuhep/sw/Boss//external/xrootd/3.2.7/x86_64-slc6-gcc46-opt/lib64:/data/lzuhep/sw/Boss//external/tcmalloc/1.7p3/x86_64-slc6-gcc46-opt/lib:/data/lzuhep/sw/Boss//external/libunwind/5c2cade/x86_64-slc6-gcc46-opt/lib:/data/lzuhep/sw/Boss//external/gcc/4.6.3/x86_64-slc6/lib64:/data/lzuhep/sw/Boss//external/CppUnit/1.12.1_p1/x86_64-slc6-gcc46-opt/lib:/data/lzuhep/sw/Boss//external/pytools/1.8_python2.7/x86_64-slc6-gcc46-opt/lib:/data/lzuhep/sw/Boss//external/lapack/3.4.0/x86_64-slc6-gcc46-opt/lib:/data/lzuhep/sw/Boss//external/blas/20110419/x86_64-slc6-gcc46-opt/lib:/data/lzuhep/sw/Boss//external/sqlite/3070900/x86_64-slc6-gcc46-opt/lib:/data/lzuhep/sw/Boss//external/mysql/5.5.14/x86_64-slc6-gcc46-opt/lib:/data/lzuhep/sw/Boss//external/XercesC/3.1.1p1/x86_64-slc6-gcc46-opt/lib:/data/lzuhep/sw/Boss//external/castor/2.1.13-6/x86_64-slc6-gcc46-opt/usr/lib64:/usr/lib:/data/lzuhep/sw/Boss/contrib/gcc46/lib64:/data/lzuhep/sw/Boss/contrib/gcc46/lib:/usr/local/openmpi/lib:/data/lzuhep/sw/Boss/external/BesGDML/2.8.0/x86_64-slc6-gcc46-opt/lib:/data/lzuhep/sw/Boss/external/DIM/dim_v19r11/x86_64-slc6-gcc46-opt/linux:/data/lzuhep/sw/Boss/external/geant4/4.9.3p01/x86_64-slc6-gcc46-opt/lib/Linux-g++:/data/lzuhep/sw/Boss/external/xmlrpc-c/xmlrpc-c-1.25.27/x86_64-slc6-gcc46-opt/lib:/data/lzuhep/sw/Boss/external/genbes/genbes-00-00-11/x86_64-slc6-gcc46-opt:/data/lzuhep/sw/Boss//external/Python/2.7.3/x86_64-slc6-gcc46-opt/lib
Python_tag=$(tag)
PYTHONROOT=/data/lzuhep/sw/Boss/LCGCMT/LCGCMT_65a/LCG_Interfaces/Python
Python_root=/data/lzuhep/sw/Boss/LCGCMT/LCGCMT_65a/LCG_Interfaces/Python
PYTHONVERSION=v1
Python_cmtpath=/data/lzuhep/sw/Boss/LCGCMT/LCGCMT_65a
Python_offset=LCG_Interfaces
Python_project=LCGCMT
Python_project_release=LCGCMT_65a
LCG_Configuration_tag=$(tag)
LCG_CONFIGURATIONROOT=/data/lzuhep/sw/Boss/LCGCMT/LCGCMT_65a/LCG_Configuration
LCG_Configuration_root=/data/lzuhep/sw/Boss/LCGCMT/LCGCMT_65a/LCG_Configuration
LCG_CONFIGURATIONVERSION=v1
LCG_Configuration_cmtpath=/data/lzuhep/sw/Boss/LCGCMT/LCGCMT_65a
LCG_Configuration_project=LCGCMT
LCG_Configuration_project_release=LCGCMT_65a
LCG_Platforms_tag=$(tag)
LCG_PLATFORMSROOT=/data/lzuhep/sw/Boss/LCGCMT/LCGCMT_65a/LCG_Platforms
LCG_Platforms_root=/data/lzuhep/sw/Boss/LCGCMT/LCGCMT_65a/LCG_Platforms
LCG_PLATFORMSVERSION=v1
LCG_Platforms_cmtpath=/data/lzuhep/sw/Boss/LCGCMT/LCGCMT_65a
LCG_Platforms_project=LCGCMT
LCG_Platforms_project_release=LCGCMT_65a
LCG_arch=x86_64
LCG_os=slc6
LCG_compiler=gcc46
LCG_mode=opt
LCG_basesystem=$(LCG_arch)-$(LCG_os)-$(LCG_compiler)
LCG_system=$(LCG_basesystem)-opt
LCG_platform=$(LCG_basesystem)-$(LCG_mode)
ATLAS_TAGS_MAP=none
host_compiler=UnknownCompiler
host_arch=x86_64
host_os=linux
host_cmtconfig=x86_64-linux-UnknownCompiler-opt
LCG_hostos=$(host_arch)-$(LCG_os)
LCG_hostarch=$(host_arch)
LCG_config_version=65a
COOL_config_version=COOL_2_8_18a
CORAL_config_version=CORAL_2_3_27a
RELAX_config_version=RELAX_1_3_0m
ROOT_config_version=5.34.09
AIDA_config_version=3.2.1
4suite_config_version=1.0.2p1
bjam_config_version=3.1.13
blas_config_version=20110419
Boost_config_version=1.50.0
Boost_file_version=1_50
CASTOR_config_version=2.1.13-6
cernlib_config_version=2006a
cgsigsoap_config_version=1.3.3-1
CLHEP_config_version=2.0.4.5
cmake_config_version=2.8.9
cmt_config_version=v1r20p20081118
coin3d_config_version=3.1.3p2
coverage_config_version=3.5.2
CppUnit_config_version=1.12.1_p1
cx_oracle_config_version=5.1.1
david_config_version=1_36a
dawn_config_version=3_88a
dcache_client_config_version=2.47.6-1
dcache_srm_config_version=1.9.5-23
dcap_config_version=2.47.6
doxygen_config_version=1.8.2
dpm_config_version=1.8.5-1
epel_config_version=20120618
Expat_config_version=2.0.1
fftw_config_version=3.1.2
Frontier_Client_config_version=2.8.5p1
fastjet_config_version=3.0.3
GCCXML_config_version=0.9.0_20120309p2
gdb_config_version=7.6
genshi_config_version=0.6
gfal_config_version=1.13.0-0
globus_config_version=4.0.7-VDT-1.10.1
graphviz_config_version=2.28.0
gridftp_ifce_config_version=2.1.4-2
GSL_config_version=1.10
HepMC_config_version=2.06.08
HepPDT_config_version=2.06.01
igprof_config_version=5.9.6
ipython_config_version=0.12.1
is_ifce_config_version=1.13.0-0
javasdk_config_version=1.6.0
javajni_config_version=$(javasdk_config_version)
json_config_version=2.5.2
kcachegrind_config_version=0.4.6
lapack_config_version=3.4.0
lcgdmcommon_config_version=1.8.5-1
lcginfosites_config_version=2.6.2-1
lcgutils_config_version=1.13.0-0
lcov_config_version=1.9
lfc_config_version=1.8.5-1
libsvm_config_version=2.86
libtool_config_version=2.4.2
libunwind_config_version=5c2cade
lxml_config_version=2.3
matplotlib_config_version=1.1.0
minuit_config_version=5.27.02
mock_config_version=0.8.0
multiprocessing_config_version=2.6.2.1
myproxy_config_version=4.2-VDT-1.10.1
mysql_config_version=5.5.14
mysql_python_config_version=1.2.3
neurobayes_config_version=3.7.0
neurobayes_expert_config_version=3.7.0
nose_config_version=1.1.2
numpy_config_version=1.6.1
oracle_config_version=11.2.0.3.0
processing_config_version=0.52
py_config_version=1.4.8
py2neo_config_version=1.4.6
pydot_config_version=1.0.28
pyanalysis_config_version=1.3
pygraphics_config_version=1.4
pygsi_config_version=0.5
pylint_config_version=0.26.0
pyminuit_config_version=0.0.1
pytest_config_version=2.2.4
pytools_config_version=1.8
Python_config_version=2.7.3
Python_config_version_twodigit=2.7
pyqt_config_version=4.9.5
pyparsing_config_version=1.5.6
pyxml_config_version=0.8.4p1
QMtest_config_version=2.4.1
qt_config_version=4.8.4
qwt_config_version=6.0.1
readline_config_version=2.5.1p1
roofit_config_version=3.10p1
setuptools_config_version=0.6c11
scipy_config_version=0.10.0
sip_config_version=4.14
soqt_config_version=1.5.0
sqlalchemy_config_version=0.7.7
sqlite_config_version=3070900
srm_ifce_config_version=1.13.0-0
stomppy_config_version=3.1.3
storm_config_version=0.19
sympy_config_version=0.7.1
tbb_config_version=41_20121003
tcmalloc_config_version=1.7p3
uuid_config_version=1.42
valgrind_config_version=3.8.0
vdt_config_version=0.3.2
voms_config_version=2.0.8-1
vomsapic_config_version=1.9.17-1
vomsapicpp_config_version=1.9.17-1
vomsapi_noglobus_config_version=1.9.17-1
vomsclients_config_version=1.9.17-1
XercesC_config_version=3.1.1p1
xqilla_config_version=2.2.4p1
xrootd_config_version=3.2.7
Python_native_version=$(Python_config_version)
Python_home=${LCG_external}/Python/$(Python_native_version)/$(LCG_system)
Python_inc=$(Python_home)/include/python$(Python_version)
Python_version=$(Python_config_version_twodigit)
Python_libversion_cmd=python -c "print ''.join('$(Python_config_version)'.split('.')[:2])"
Python_libversion=$(Python_config_version_twodigit)
Python_linkopts= -L$(Python_home)/lib -lpython$(Python_libversion) -lutil -lpthread 
Python_export_paths=$(Python_home)
MANPATH=/data/lzuhep/sw/Boss//external/ROOT/5.34.09/x86_64-slc6-gcc46-opt/root/man:/data/lzuhep/sw/Boss//external/tcmalloc/1.7p3/x86_64-slc6-gcc46-opt/share/man:/data/lzuhep/sw/Boss//external/libunwind/5c2cade/x86_64-slc6-gcc46-opt/man:/data/lzuhep/sw/Boss//external/Python/2.7.3/x86_64-slc6-gcc46-opt/share/man:/data/lzuhep/sw/Boss//external/CppUnit/1.12.1_p1/x86_64-slc6-gcc46-opt/share/man:/data/lzuhep/sw/Boss//external/pytools/1.8_python2.7/x86_64-slc6-gcc46-opt/man:/data/lzuhep/sw/Boss//external/mysql/5.5.14/x86_64-slc6-gcc46-opt/man:/usr/man:/data/lzuhep/sw/Boss//external/gccxml/0.9.0_20120309p2/x86_64-slc6-gcc46-opt/share/man:/data/lzuhep/sw/Boss//external/castor/2.1.13-6/x86_64-slc6-gcc46-opt/usr/share/man:/data/lzuhep/sw/Boss//external/cernlib/2006a/x86_64-slc6-gcc46-opt/src/man:/data/lzuhep/sw/Boss//external/ROOT/5.34.09/src/root/man
tcmalloc_tag=$(tag)
TCMALLOCROOT=/data/lzuhep/sw/Boss/LCGCMT/LCGCMT_65a/LCG_Interfaces/tcmalloc
tcmalloc_root=/data/lzuhep/sw/Boss/LCGCMT/LCGCMT_65a/LCG_Interfaces/tcmalloc
TCMALLOCVERSION=v1
tcmalloc_cmtpath=/data/lzuhep/sw/Boss/LCGCMT/LCGCMT_65a
tcmalloc_offset=LCG_Interfaces
tcmalloc_project=LCGCMT
tcmalloc_project_release=LCGCMT_65a
libunwind_tag=$(tag)
LIBUNWINDROOT=/data/lzuhep/sw/Boss/LCGCMT/LCGCMT_65a/LCG_Interfaces/libunwind
libunwind_root=/data/lzuhep/sw/Boss/LCGCMT/LCGCMT_65a/LCG_Interfaces/libunwind
LIBUNWINDVERSION=v1
libunwind_cmtpath=/data/lzuhep/sw/Boss/LCGCMT/LCGCMT_65a
libunwind_offset=LCG_Interfaces
libunwind_project=LCGCMT
libunwind_project_release=LCGCMT_65a
libunwind_native_version=$(libunwind_config_version)
libunwind_home=$(LCG_external)/libunwind/$(libunwind_native_version)/$(LCG_system)
libunwind_linkopts=-L$(libunwind_home)/lib -lunwind -lunwind-x86_64
libunwind_cppflags=-I $(libunwind_home)/include
libunwind_export_paths= $(libunwind_home)/include $(libunwind_home)/lib 
tcmalloc_native_version=$(tcmalloc_config_version)
tcmalloc_home=$(LCG_external)/tcmalloc/$(tcmalloc_native_version)/$(LCG_system)
copyInclude=cp -Rup 
python_bin_module_dir=$(tag)/python/lib-dynload
cmt_actions_constituents=       
cmt_actions_constituentsclean= new_rootsysclean TestProjectclean TestPackageclean qmtest_summarizeclean qmtest_runclean makeclean 
remove_command=$(cmt_uninstallarea_command)
dq="
BINDIR=$(tag)
vsDebug=2
merge_rootmap_cmd=python $(GaudiPolicy_root)/scripts/merge_files.py
libdirname=lib
bindirname=bin
lib_no_static_fragment=library_no_static
cppdebugflags_s=-g
cppoptimized_s=-O2 -DNDEBUG
cppprofiled_s=-pg
cdebugflags_s=-g
coptimized_s=-O2 -DNDEBUG
fdebugflags= $(foptimized_s)
fdebugflags_s=-g
foptimized_s=-O2 -DNDEBUG
fprofiled_s=-pg
GaudiKernel_linkopts= -lGaudiKernel 
makeLinkMap=-Wl,-Map,Linux.map
componentshr_linkopts=-fPIC -ldl  -Wl,--no-undefined -pthread  -Wl,-z,max-page-size=0x1000  
libraryshr_linkopts=-fPIC -ldl  -Wl,--no-undefined -pthread  -Wl,-z,max-page-size=0x1000 
application_linkopts=-Wl,--export-dynamic 
shared_install_subdir=/$(tag)
genconfDir=$(shared_install_subdir)/genConf/
merge_genconfDb_cmd=python $(GaudiPolicy_root)/scripts/merge_files.py
genconfig_configurableModuleName=GaudiKernel.Proxy
genconfig_configurableDefaultName=Configurable.DefaultName
genconfig_configurableAlgorithm=ConfigurableAlgorithm
genconfig_configurableAlgTool=ConfigurableAlgTool
genconfig_configurableAuditor=ConfigurableAuditor
genconfig_configurableService=ConfigurableService
use_GaudiCoreSvc=GaudiCoreSvc * -no_auto_imports
strip_script=$(GAUDIPOLICYROOT)/scripts/StripPath
GenConfUser_script=genconfuser.py
COOLVERS=COOL_2_8_18a
CORALVERS=CORAL_2_3_27a
ROOTVERS=5.34.09
BoostVERS=1.50.0
uuidVERS=1.42
GCCXMLVERS=0.9.0_20120309p2
AIDAVERS=3.2.1
XercesCVERS=3.1.1p1
GSLVERS=1.10
PythonVERS=2.7.3
HepMCVERS=2.06.08
QMtestVERS=2.4.1
LCGCMTVERS=65a
GAUDI_DOXY_HOME=/data/lzuhep/sw/Boss/gaudi/GAUDI_v23r9/GaudiRelease/doc
config_command=cp 
BesCxxPolicy_pp_cppflags= -DHAVE_PRETTY_FUNCTION -DHAVE_LONG_LONG -DHAVE_BOOL -DHAVE_EXPLICIT -DHAVE_MUTABLE -DHAVE_SIGNED -DHAVE_TYPENAME -DHAVE_NEW_STYLE_CASTS -DHAVE_DYNAMIC_CAST -DHAVE_TYPEID -DHAVE_ANSI_TEMPLATE_INSTANTIATION -DHAVE_TEMPLATE_DEFAULT_ARGS -DHAVE_BROKEN_TEMPLATE_RESCOPE -DHAVE_TEMPLATE_NULL_ARGS -DHAVE_TEMPLATE_NULL_SPEC -DHAVE_TEMPLATE_PARTIAL_SPEC -DHAVE_MEMBER_TEMPLATES -DHAVE_ANSI_OPERATOR_ARROW -DHAVE_NAMESPACES -DHAVE_NAMESPACE_STD -DHAVE_NEW_IOSTREAMS -DHAVE_OSTREAM_CHAR_OVERLOAD -DHAVE_ITERATOR_TRAITS -DHAVE_ITERATOR -DHAVE_REVERSE_ITERATOR_STYLE -DHAVE_CXX_STDC_HEADERS '-DPACKAGE_VERSION=$(q2)$(version)$(q2)' 
q2="
BesFortranPolicy_tag=$(tag)
BESFORTRANPOLICYROOT=/data/lzuhep/sw/Boss/dist/7.0.3/BesFortranPolicy/BesFortranPolicy-00-01-03
BesFortranPolicy_root=/data/lzuhep/sw/Boss/dist/7.0.3/BesFortranPolicy/BesFortranPolicy-00-01-03
BESFORTRANPOLICYVERSION=BesFortranPolicy-00-01-03
BesFortranPolicy_cmtpath=/data/lzuhep/sw/Boss/dist/7.0.3
BesFortranPolicy_project=BOSS
BesFortranPolicy_project_release=7.0.3
f77_linkopts=-lgfortran -lnsl -lcrypt -ldl
f90_home=$(f90_home_linux)
for90=$(for90_linux)
f90pp=$(f90pp_linux)
f90flags=$(f90flags_linux)
f90ppflags=$(f90ppflags_linux)
f90comp=$(f90comp_linux)
f90link=$(f90link_linux)
f90_linkopts=$(f90_linkopts_linux)
BesFortranPolicy_linkopts=$(f77_linkopts)
BesFortranPolicy_export_paths=$(PGI_libset)
BesPolicy_scripts= -s=$(BESPOLICYROOT)/share -s=$(BESPOLICYROOT)/src symlink.sh inverse_symlink.sh get_files 
symlink_command=symlink.sh
symlinknew=$(symlink_command)
copy_command=cp -R
MAKEFLAGS= --no-print-directory 
remote_launcher=ssh -f 
application_fragment=application
library_fragment=library
library_no_share_fragment=library_no_share
install_include_filter=*.h
GaudiInterface_tag=$(tag)
GAUDIINTERFACEROOT=/data/lzuhep/sw/Boss/dist/7.0.3/External/GaudiInterface/GaudiInterface-01-03-07
GaudiInterface_root=/data/lzuhep/sw/Boss/dist/7.0.3/External/GaudiInterface/GaudiInterface-01-03-07
GAUDIINTERFACEVERSION=GaudiInterface-01-03-07
GaudiInterface_cmtpath=/data/lzuhep/sw/Boss/dist/7.0.3
GaudiInterface_offset=External
GaudiInterface_project=BOSS
GaudiInterface_project_release=7.0.3
GaudiKernel_tag=$(tag)
GAUDIKERNELROOT=/data/lzuhep/sw/Boss/gaudi/GAUDI_v23r9/GaudiKernel
GaudiKernel_root=/data/lzuhep/sw/Boss/gaudi/GAUDI_v23r9/GaudiKernel
GAUDIKERNELVERSION=v28r8
GaudiKernel_cmtpath=/data/lzuhep/sw/Boss/gaudi/GAUDI_v23r9
GaudiKernel_project=GAUDI
GaudiKernel_project_release=GAUDI_v23r9
Reflex_tag=$(tag)
REFLEXROOT=/data/lzuhep/sw/Boss/LCGCMT/LCGCMT_65a/LCG_Interfaces/Reflex
Reflex_root=/data/lzuhep/sw/Boss/LCGCMT/LCGCMT_65a/LCG_Interfaces/Reflex
REFLEXVERSION=v1
Reflex_cmtpath=/data/lzuhep/sw/Boss/LCGCMT/LCGCMT_65a
Reflex_offset=LCG_Interfaces
Reflex_project=LCGCMT
Reflex_project_release=LCGCMT_65a
ROOT_tag=$(tag)
ROOTROOT=/data/lzuhep/sw/Boss/LCGCMT/LCGCMT_65a/LCG_Interfaces/ROOT
ROOT_root=/data/lzuhep/sw/Boss/LCGCMT/LCGCMT_65a/LCG_Interfaces/ROOT
ROOTVERSION=v1
ROOT_cmtpath=/data/lzuhep/sw/Boss/LCGCMT/LCGCMT_65a
ROOT_offset=LCG_Interfaces
ROOT_project=LCGCMT
ROOT_project_release=LCGCMT_65a
GCCXML_tag=$(tag)
GCCXMLROOT=/data/lzuhep/sw/Boss/LCGCMT/LCGCMT_65a/LCG_Interfaces/GCCXML
GCCXML_root=/data/lzuhep/sw/Boss/LCGCMT/LCGCMT_65a/LCG_Interfaces/GCCXML
GCCXMLVERSION=v1
GCCXML_cmtpath=/data/lzuhep/sw/Boss/LCGCMT/LCGCMT_65a
GCCXML_offset=LCG_Interfaces
GCCXML_project=LCGCMT
GCCXML_project_release=LCGCMT_65a
GCCXML_native_version=$(GCCXML_config_version)
GCCXML_home=$(LCG_external)/gccxml/$(GCCXML_native_version)/$(LCG_system)
GCCXML_name=gccxml
GCCXML_export_paths=$(GCCXML_home)/bin $(GCCXML_home)/share 
xrootd_tag=$(tag)
XROOTDROOT=/data/lzuhep/sw/Boss/LCGCMT/LCGCMT_65a/LCG_Interfaces/xrootd
xrootd_root=/data/lzuhep/sw/Boss/LCGCMT/LCGCMT_65a/LCG_Interfaces/xrootd
XROOTDVERSION=v1
xrootd_cmtpath=/data/lzuhep/sw/Boss/LCGCMT/LCGCMT_65a
xrootd_offset=LCG_Interfaces
xrootd_project=LCGCMT
xrootd_project_release=LCGCMT_65a
xrootd_native_version=$(xrootd_config_version)
xrootd_home=$(LCG_external)/xrootd/$(xrootd_native_version)/$(LCG_system)
xrootd_linkopts=-L$(xrootd_home)/$(unixdirname) 
xrootd_export_paths= $(xrootd_home)/bin $(xrootd_home)/include $(xrootd_home)/$(unixdirname)   $(xrootd_home)/share
ROOT_native_version=$(ROOT_config_version)
ROOT_base=$(LCG_releases)/ROOT/$(ROOT_native_version)
ROOT_home=$(ROOT_base)/$(LCG_platform)/root
ROOT_linkopts=-L$(ROOT_home)/lib -lCore -lCint -lTree -lpthread  -lRIO
ROOT_Reflex_linkopts=-L$(ROOT_home)/lib -lReflex
ROOTSYS=/data/lzuhep/sw/Boss//external/ROOT/5.34.09/x86_64-slc6-gcc46-opt/root
ROOT_name=root
ROOT_header_file_filter=$(ROOT_home)/include
ROOT_header_file_stamp=$(ROOT_home)/include/Type.h
PYTHONPATH=/data2/kc2019/workfs/7.0.3/InstallArea/x86_64-slc6-gcc46-opt/python/lib-dynload:/data/lzuhep/sw/Boss/dist/7.0.3/InstallArea/x86_64-slc6-gcc46-opt/python/lib-dynload:/data/lzuhep/sw/Boss/gaudi/GAUDI_v23r9/InstallArea/x86_64-slc6-gcc46-opt/python/lib-dynload:/data2/kc2019/workfs/7.0.3/InstallArea/x86_64-slc6-gcc46-opt/python.zip:/data/lzuhep/sw/Boss/dist/7.0.3/InstallArea/x86_64-slc6-gcc46-opt/python.zip:/data/lzuhep/sw/Boss/gaudi/GAUDI_v23r9/InstallArea/x86_64-slc6-gcc46-opt/python.zip:/data/lzuhep/sw/Boss//external/ROOT/5.34.09/x86_64-slc6-gcc46-opt/root/lib:/data/lzuhep/sw/Boss//external/pytools/1.8_python2.7/x86_64-slc6-gcc46-opt/lib/python2.7/site-packages
rootcint="$(ROOT_home)/bin/rootcint"
genmap_cmd=$(ROOTSYS)/bin/genmap
ROOT_export_paths= $(ROOT_home) 
Reflex_linkopts=$(ROOT_Reflex_linkopts)
genreflex_cmd=$(ROOT_home)/bin/genreflex
gccxmloptsval=--gccxml-compiler $(cpp_name) 
gccxmlopts=--gccxmlopt='$(gccxmloptsval)'
Boost_tag=$(tag)
BOOSTROOT=/data/lzuhep/sw/Boss/LCGCMT/LCGCMT_65a/LCG_Interfaces/Boost
Boost_root=/data/lzuhep/sw/Boss/LCGCMT/LCGCMT_65a/LCG_Interfaces/Boost
BOOSTVERSION=v1
Boost_cmtpath=/data/lzuhep/sw/Boss/LCGCMT/LCGCMT_65a
Boost_offset=LCG_Interfaces
Boost_project=LCGCMT
Boost_project_release=LCGCMT_65a
Boost_native_version=$(Boost_config_version)_python$(Python_config_version_twodigit)
Boost_home=$(LCG_external)/Boost/$(Boost_native_version)/$(LCG_system)
Boost_compiler_version=$(LCG_compiler)
Boost_linkopts=-L$(Boost_home)/lib  $(Boost_linkopts_system) $(Boost_linkopts_filesystem) $(Boost_linkopts_thread) 
Boost_linkopts_python= -lboost_python-$(Boost_compiler_version)-mt-$(Boost_file_version) 
Boost_linkopts_system= -lboost_system-$(Boost_compiler_version)-mt-$(Boost_file_version) 
Boost_linkopts_filesystem= -lboost_filesystem-$(Boost_compiler_version)-mt-$(Boost_file_version) 
Boost_linkopts_filesystem_mt= -lboost_filesystem-$(Boost_compiler_version)-mt-$(Boost_file_version) 
Boost_linkopts_iostreams= -lboost_iostreams-$(Boost_compiler_version)-mt-$(Boost_file_version) 
Boost_linkopts_regex= -lboost_regex-$(Boost_compiler_version)-mt-$(Boost_file_version) 
Boost_linkopts_thread= -lboost_thread-$(Boost_compiler_version)-mt-$(Boost_file_version) 
Boost_linkopts_program_options= -lboost_program_options-$(Boost_compiler_version)-mt-$(Boost_file_version) 
Boost_linkopts_serialization= -lboost_serialization-$(Boost_compiler_version)-mt-$(Boost_file_version) 
Boost_linkopts_date_time= -lboost_date_time-$(Boost_compiler_version)-mt-$(Boost_file_version) 
Boost_linkopts_graph= -lboost_graph-$(Boost_compiler_version)-mt-$(Boost_file_version) 
Boost_header_file_filter=$(Boost_home)/include/boost-$(Boost_file_version)
Boost_header_file_stamp=$(Boost_home)/include/boost-$(Boost_file_version)/boost/any.hpp
Boost_export_paths=$(Boost_home)
includes= $(ppcmd)"/data2/kc2019/workfs/7.0.3/InstallArea/include/McDecayModeSvc" $(ppcmd)"/data2/kc2019/workfs/7.0.3/InstallArea/x86_64-slc6-gcc46-opt/include" $(ppcmd)"/data/lzuhep/sw/Boss/dist/7.0.3/InstallArea/x86_64-slc6-gcc46-opt/include" $(ppcmd)"/data/lzuhep/sw/Boss/gaudi/GAUDI_v23r9/InstallArea/x86_64-slc6-gcc46-opt/include" $(use_includes)
GaudiKernel_stamps=${GAUDIKERNELROOT}/${BINDIR}/GaudiKernel.stamp 
GaudiKernel_linker_library=GaudiKernel
zip_GaudiKernel_python_modules_dependencies= GaudiKernel_python_init 
GaudiKernel_python_init_dependencies= GaudiKernel_python 
GaudiKernelDict_use_linkopts=$(use_linkopts)
GaudiKernelGen_dependencies=install_more_includes
genconfig_cmd=genconf.exe
GaudiSvc_tag=$(tag)
GAUDISVCROOT=/data/lzuhep/sw/Boss/gaudi/GAUDI_v23r9/GaudiSvc
GaudiSvc_root=/data/lzuhep/sw/Boss/gaudi/GAUDI_v23r9/GaudiSvc
GAUDISVCVERSION=v19r4
GaudiSvc_cmtpath=/data/lzuhep/sw/Boss/gaudi/GAUDI_v23r9
GaudiSvc_project=GAUDI
GaudiSvc_project_release=GAUDI_v23r9
CLHEP_tag=$(tag)
CLHEPROOT=/data/lzuhep/sw/Boss/LCGCMT/LCGCMT_65a/LCG_Interfaces/CLHEP
CLHEP_root=/data/lzuhep/sw/Boss/LCGCMT/LCGCMT_65a/LCG_Interfaces/CLHEP
CLHEPVERSION=v1
CLHEP_cmtpath=/data/lzuhep/sw/Boss/LCGCMT/LCGCMT_65a
CLHEP_offset=LCG_Interfaces
CLHEP_project=LCGCMT
CLHEP_project_release=LCGCMT_65a
CLHEP_native_version=$(CLHEP_config_version)
CLHEP_home=$(LCG_external)/clhep/$(CLHEP_native_version)/$(LCG_system)
CLHEP_linkopts=-L$(CLHEP_home)/lib         -lCLHEP-Cast-$(CLHEP_native_version)        -lCLHEP-Evaluator-$(CLHEP_native_version)        -lCLHEP-Exceptions-$(CLHEP_native_version)        -lCLHEP-GenericFunctions-$(CLHEP_native_version)        -lCLHEP-Geometry-$(CLHEP_native_version)        -lCLHEP-Random-$(CLHEP_native_version)        -lCLHEP-RandomObjects-$(CLHEP_native_version)        -lCLHEP-RefCount-$(CLHEP_native_version)         -lCLHEP-Vector-$(CLHEP_native_version)        -lCLHEP-Matrix-$(CLHEP_native_version)  
CLHEP_name=clhep
CLHEP_export_paths=$(CLHEP_home)/include $(CLHEP_home)/lib
GaudiSvc_shlibflags=$(componentshr_linkopts) $(use_linkopts) 
GaudiSvcstamps= $(bin)/GaudiSvcsetup.make  $(bin)/GaudiSvcsetup.make 
BesCLHEP_tag=$(tag)
BESCLHEPROOT=/data/lzuhep/sw/Boss/dist/7.0.3/External/BesCLHEP/BesCLHEP-00-00-11
BesCLHEP_root=/data/lzuhep/sw/Boss/dist/7.0.3/External/BesCLHEP/BesCLHEP-00-00-11
BESCLHEPVERSION=BesCLHEP-00-00-11
BesCLHEP_cmtpath=/data/lzuhep/sw/Boss/dist/7.0.3
BesCLHEP_offset=External
BesCLHEP_project=BOSS
BesCLHEP_project_release=7.0.3
HepMC_tag=$(tag)
HEPMCROOT=/data/lzuhep/sw/Boss/LCGCMT/LCGCMT_65a/LCG_Interfaces/HepMC
HepMC_root=/data/lzuhep/sw/Boss/LCGCMT/LCGCMT_65a/LCG_Interfaces/HepMC
HEPMCVERSION=v1
HepMC_cmtpath=/data/lzuhep/sw/Boss/LCGCMT/LCGCMT_65a
HepMC_offset=LCG_Interfaces
HepMC_project=LCGCMT
HepMC_project_release=LCGCMT_65a
HepMC_native_version=$(HepMC_config_version)
HepMC_home=$(LCG_external)/HepMC/$(HepMC_native_version)/$(LCG_system)
HepMC_linkopts=-L$(HepMC_home)/lib -lHepMC 
HepMC_export_paths=$(HepMC_home)/include $(HepMC_home)/lib
HepPDT_tag=$(tag)
HEPPDTROOT=/data/lzuhep/sw/Boss/LCGCMT/LCGCMT_65a/LCG_Interfaces/HepPDT
HepPDT_root=/data/lzuhep/sw/Boss/LCGCMT/LCGCMT_65a/LCG_Interfaces/HepPDT
HEPPDTVERSION=v1
HepPDT_cmtpath=/data/lzuhep/sw/Boss/LCGCMT/LCGCMT_65a
HepPDT_offset=LCG_Interfaces
HepPDT_project=LCGCMT
HepPDT_project_release=LCGCMT_65a
HepPDT_native_version=$(HepPDT_config_version)
HepPDT_home=$(LCG_external)/HepPDT/$(HepPDT_native_version)/$(LCG_system)
HepPDT_linkopts=-L$(HepPDT_home)/lib -lHepPDT -lHepPID 
HepPDT_export_paths=$(HepPDT_home)/include $(HepPDT_home)/lib
BesExternalArea_tag=$(tag)
BESEXTERNALAREAROOT=/data/lzuhep/sw/Boss/dist/7.0.3/External/BesExternalArea/BesExternalArea-00-00-22
BesExternalArea_root=/data/lzuhep/sw/Boss/dist/7.0.3/External/BesExternalArea/BesExternalArea-00-00-22
BESEXTERNALAREAVERSION=BesExternalArea-00-00-22
BesExternalArea_cmtpath=/data/lzuhep/sw/Boss/dist/7.0.3
BesExternalArea_offset=External
BesExternalArea_project=BOSS
BesExternalArea_project_release=7.0.3
LCG_ROOT=${EXTERNALLIBDIR}
LCG_EXTERNAL=${LCG_ROOT}/external
LCG_app_system=rh73_gcc32
LCG_ext_system=rh73_gcc32
BES_EXTERNAL=${SITEROOT}/external
BESTESTDATA=${SITEROOT}/bes/offline/data/testfile
BESCALDATA=${SITEROOT}/data/${BES_RELEASE}
COMMON_PACKAGES=${SITEROOT}/external
ALIST_DIR=${BES_EXTERNAL}/CLHEP/Alist/Alist-00-00-06
STRING_DIR=${BES_EXTERNAL}/CLHEP/String/String-00-00-05
CLHEP_pp_cppflags= -DCLHEP_MAX_MIN_DEFINED -DCLHEP_ABS_DEFINED -DCLHEP_SQR_DEFINED 
CLHEP_pp_fflags= -DCLHEP_MAX_MIN_DEFINED -DCLHEP_ABS_DEFINED -DCLHEP_SQR_DEFINED 
McTruth_tag=$(tag)
MCTRUTHROOT=/data/lzuhep/sw/Boss/dist/7.0.3/Event/McTruth/McTruth-00-02-19
McTruth_root=/data/lzuhep/sw/Boss/dist/7.0.3/Event/McTruth/McTruth-00-02-19
MCTRUTHVERSION=McTruth-00-02-19
McTruth_cmtpath=/data/lzuhep/sw/Boss/dist/7.0.3
McTruth_offset=Event
McTruth_project=BOSS
McTruth_project_release=7.0.3
EventModel_tag=$(tag)
EVENTMODELROOT=/data/lzuhep/sw/Boss/dist/7.0.3/Event/EventModel/EventModel-01-05-33
EventModel_root=/data/lzuhep/sw/Boss/dist/7.0.3/Event/EventModel/EventModel-01-05-33
EVENTMODELVERSION=EventModel-01-05-33
EventModel_cmtpath=/data/lzuhep/sw/Boss/dist/7.0.3
EventModel_offset=Event
EventModel_project=BOSS
EventModel_project_release=7.0.3
EventModel_linkopts= -L$(bin) -lEventModel  
Identifier_tag=$(tag)
IDENTIFIERROOT=/data/lzuhep/sw/Boss/dist/7.0.3/DetectorDescription/Identifier/Identifier-00-02-17
Identifier_root=/data/lzuhep/sw/Boss/dist/7.0.3/DetectorDescription/Identifier/Identifier-00-02-17
IDENTIFIERVERSION=Identifier-00-02-17
Identifier_cmtpath=/data/lzuhep/sw/Boss/dist/7.0.3
Identifier_offset=DetectorDescription
Identifier_project=BOSS
Identifier_project_release=7.0.3
Identifier_linkopts= -L$(bin) -lIdentifier  
checkId_dependencies=Identifier
RelTable_tag=$(tag)
RELTABLEROOT=/data/lzuhep/sw/Boss/dist/7.0.3/Event/RelTable/RelTable-00-00-02
RelTable_root=/data/lzuhep/sw/Boss/dist/7.0.3/Event/RelTable/RelTable-00-00-02
RELTABLEVERSION=RelTable-00-00-02
RelTable_cmtpath=/data/lzuhep/sw/Boss/dist/7.0.3
RelTable_offset=Event
RelTable_project=BOSS
RelTable_project_release=7.0.3
McTruth_linkopts= -L$(bin) -lMcTruth  
McDecayModeSvcLib_files=*.cxx
McDecayModeSvc_dependencies= McDecayModeSvcLib
McDecayModeSvcstamps= $(bin)/McDecayModeSvcLib.stamp $(bin)/McDecayModeSvcsetup.make 
McDecayModeSvc_linkopts= -L$(bin) -lMcDecayModeSvcLib
McDecayModeSvc_shlibflags=$(componentshr_linkopts) $(use_linkopts) 
GaudiPolicyDir=${GAUDIPOLICYROOT}/${BINDIR}
BesCxxPolicyDir=${BESCXXPOLICYROOT}/${BINDIR}
BesPolicyDir=${BESPOLICYROOT}/${BINDIR}
GaudiKernelDir=${GAUDIKERNELROOT}/${BINDIR}
GaudiSvcDir=${GAUDISVCROOT}/${BINDIR}
GaudiInterfaceDir=${GAUDIINTERFACEROOT}/${BINDIR}
EventModelDir=${EVENTMODELROOT}/${BINDIR}
IdentifierDir=${IDENTIFIERROOT}/${BINDIR}
RelTableDir=${RELTABLEROOT}/${BINDIR}
McTruthDir=${MCTRUTHROOT}/${BINDIR}
McDecayModeSvcDir=${MCDECAYMODESVCROOT}/${BINDIR}
old_dir=`echo $(McDecayModeSvc_project)/$(McDecayModeSvc_project_release) | sed -e 's#//#/#g'`
old_base=`echo $(McDecayModeSvc_cmtpath) | sed -e 's#/$(old_dir)##'`
sedcmd='s#$(old_base)##' -e 's#^/##' -e 's#/$##' -e 's#[^/]*#..#g'
new_base=`/bin/pwd | sed -e ${sedcmd}`
new_fincludes=`( echo $(includes) | sed -e 's#$(old_base)#$(new_base)#g')`
fincludes=`cmt show macro_value new_fincludes`
tag=x86_64-slc6-gcc46-opt
package=McDecayModeSvc
version=McDecayModeSvc-00-00-01
PACKAGE_ROOT=$(MCDECAYMODESVCROOT)
srcdir=../src
bin=../$(McDecayModeSvc_tag)/
javabin=../classes/
mgrdir=cmt
BIN=/data2/kc2019/workfs/7.0.3/Analysis/McDecayModeSvc/McDecayModeSvc-00-00-01/x86_64-slc6-gcc46-opt/
project=workfs
cmt_installarea_paths= $(cmt_installarea_prefix)/$(CMTCONFIG)/bin $(GAUDI_installarea_prefix)/$(CMTCONFIG)/lib $(GAUDI_installarea_prefix)/share/lib $(GAUDI_installarea_prefix)/share/bin $(BOSS_installarea_prefix)/$(CMTCONFIG)/lib $(BOSS_installarea_prefix)/share/lib $(BOSS_installarea_prefix)/share/bin $(workfs_installarea_prefix)/$(CMTCONFIG)/lib $(workfs_installarea_prefix)/share/lib $(workfs_installarea_prefix)/share/bin
use_linkopts= $(cmt_installarea_linkopts)   $(McDecayModeSvc_linkopts)  $(McTruth_linkopts)  $(EventModel_linkopts)  $(Identifier_linkopts)  $(RelTable_linkopts)  $(BesPolicy_linkopts)  $(BesCxxPolicy_linkopts)  $(GaudiInterface_linkopts)  $(GaudiSvc_linkopts)  $(GaudiKernel_linkopts)  $(GaudiPolicy_linkopts)  $(Reflex_linkopts)  $(Boost_linkopts)  $(BesFortranPolicy_linkopts)  $(BesCLHEP_linkopts)  $(CLHEP_linkopts)  $(HepMC_linkopts)  $(HepPDT_linkopts)  $(LCG_Settings_linkopts)  $(LCG_Configuration_linkopts)  $(LCG_Platforms_linkopts)  $(BesExternalArea_linkopts) 
LCGCMT_installarea_prefix=$(cmt_installarea_prefix)
LCGCMT_installarea_prefix_remove=$(LCGCMT_installarea_prefix)
GAUDI_installarea_prefix=$(cmt_installarea_prefix)
GAUDI_installarea_prefix_remove=$(GAUDI_installarea_prefix)
BOSS_installarea_prefix=$(cmt_installarea_prefix)
BOSS_installarea_prefix_remove=$(BOSS_installarea_prefix)
workfs_installarea_prefix=$(cmt_installarea_prefix)
workfs_installarea_prefix_remove=$(workfs_installarea_prefix)
cmt_installarea_linkopts= -L/data2/kc2019/workfs/7.0.3/$(workfs_installarea_prefix)/$(CMTCONFIG)/lib  -L/data/lzuhep/sw/Boss/dist/7.0.3/$(BOSS_installarea_prefix)/$(CMTCONFIG)/lib  -L/data/lzuhep/sw/Boss/gaudi/GAUDI_v23r9/$(GAUDI_installarea_prefix)/$(CMTCONFIG)/lib 
LCGCMT_home=/data/lzuhep/sw/Boss/LCGCMT/LCGCMT_65a
GAUDI_home=/data/lzuhep/sw/Boss/gaudi/GAUDI_v23r9
BOSS_home=/data/lzuhep/sw/Boss/dist/7.0.3
workfs_home=/data2/kc2019/workfs/7.0.3
workfs_install_include= /data2/kc2019/workfs/7.0.3/$(workfs_installarea_prefix)$(shared_install_subdir)/include 
BOSS_install_include= /data/lzuhep/sw/Boss/dist/7.0.3/$(BOSS_installarea_prefix)$(shared_install_subdir)/include 
GAUDI_install_include= /data/lzuhep/sw/Boss/gaudi/GAUDI_v23r9/$(GAUDI_installarea_prefix)$(shared_install_subdir)/include 
GAUDI_install_python=/data/lzuhep/sw/Boss/gaudi/GAUDI_v23r9/$(GAUDI_installarea_prefix)$(shared_install_subdir)/python.zip
BOSS_install_python=/data/lzuhep/sw/Boss/dist/7.0.3/$(BOSS_installarea_prefix)$(shared_install_subdir)/python.zip
workfs_install_python=/data2/kc2019/workfs/7.0.3/$(workfs_installarea_prefix)$(shared_install_subdir)/python.zip
GAUDI_install_pyd_module=/data/lzuhep/sw/Boss/gaudi/GAUDI_v23r9/$(GAUDI_installarea_prefix)/$(python_bin_module_dir)
BOSS_install_pyd_module=/data/lzuhep/sw/Boss/dist/7.0.3/$(BOSS_installarea_prefix)/$(python_bin_module_dir)
workfs_install_pyd_module=/data2/kc2019/workfs/7.0.3/$(workfs_installarea_prefix)/$(python_bin_module_dir)
scripts_offset=.
scripts_maindir=scripts
scripts_dir=$(scripts_maindir)
GAUDI_install_scripts=/data/lzuhep/sw/Boss/gaudi/GAUDI_v23r9/$(GAUDI_installarea_prefix)$(shared_install_subdir)/$(scripts_dir)
BOSS_install_scripts=/data/lzuhep/sw/Boss/dist/7.0.3/$(BOSS_installarea_prefix)$(shared_install_subdir)/$(scripts_dir)
workfs_install_scripts=/data2/kc2019/workfs/7.0.3/$(workfs_installarea_prefix)$(shared_install_subdir)/$(scripts_dir)
genconfInstallDir=$(CMTINSTALLAREA)$(shared_install_subdir)/python
JOBOPTSEARCHPATH=,/data2/kc2019/workfs/7.0.3/InstallArea/jobOptions,/data/lzuhep/sw/Boss/dist/7.0.3/InstallArea/jobOptions,/data/lzuhep/sw/Boss/gaudi/GAUDI_v23r9/InstallArea/jobOptions,/data/lzuhep/sw/Boss/LCGCMT/LCGCMT_65a/InstallArea/jobOptions
DATAPATH=/data2/kc2019/workfs/7.0.3/InstallArea/share:/data/lzuhep/sw/Boss/dist/7.0.3/InstallArea/share:/data/lzuhep/sw/Boss/gaudi/GAUDI_v23r9/InstallArea/share:/data/lzuhep/sw/Boss/LCGCMT/LCGCMT_65a/InstallArea/share:/data/lzuhep/sw/Boss/gaudi/GAUDI_v23r9/PartPropSvc/share
XMLPATH=/data2/kc2019/workfs/7.0.3/InstallArea/XML:/data/lzuhep/sw/Boss/dist/7.0.3/InstallArea/XML:/data/lzuhep/sw/Boss/gaudi/GAUDI_v23r9/InstallArea/XML:/data/lzuhep/sw/Boss/LCGCMT/LCGCMT_65a/InstallArea/XML
constituents= install_includes  McDecayModeSvcLib McDecayModeSvc config install_includes 
CMTINSTALLAREA=/data2/kc2019/workfs/7.0.3/$(cmt_installarea_prefix)
use_requirements=requirements $(CMT_root)/mgr/requirements $(McTruth_root)/cmt/requirements $(EventModel_root)/cmt/requirements $(Identifier_root)/cmt/requirements $(RelTable_root)/cmt/requirements $(BesPolicy_root)/cmt/requirements $(BesCxxPolicy_root)/cmt/requirements $(GaudiInterface_root)/cmt/requirements $(GaudiSvc_root)/cmt/requirements $(GaudiKernel_root)/cmt/requirements $(GaudiPolicy_root)/cmt/requirements $(Reflex_root)/cmt/requirements $(ROOT_root)/cmt/requirements $(Boost_root)/cmt/requirements $(Python_root)/cmt/requirements $(tcmalloc_root)/cmt/requirements $(libunwind_root)/cmt/requirements $(BesFortranPolicy_root)/cmt/requirements $(GCCXML_root)/cmt/requirements $(xrootd_root)/cmt/requirements $(BesCLHEP_root)/cmt/requirements $(CLHEP_root)/cmt/requirements $(HepMC_root)/cmt/requirements $(HepPDT_root)/cmt/requirements $(LCG_Settings_root)/cmt/requirements $(LCG_Configuration_root)/cmt/requirements $(LCG_Platforms_root)/cmt/requirements $(BesExternalArea_root)/cmt/requirements 
use_includes= $(ppcmd)"/data/lzuhep/sw/Boss/dist/7.0.3/Event/McTruth/McTruth-00-02-19/McTruth" $(ppcmd)"/data/lzuhep/sw/Boss/dist/7.0.3/InstallArea/include/McTruth" $(ppcmd)"/data/lzuhep/sw/Boss/dist/7.0.3/Event/EventModel/EventModel-01-05-33" $(ppcmd)"/data/lzuhep/sw/Boss/dist/7.0.3/InstallArea/include/EventModel" $(ppcmd)"/data/lzuhep/sw/Boss/dist/7.0.3/DetectorDescription/Identifier/Identifier-00-02-17" $(ppcmd)"/data/lzuhep/sw/Boss/dist/7.0.3/InstallArea/include/Identifier" $(ppcmd)"/data/lzuhep/sw/Boss/dist/7.0.3/Event/RelTable/RelTable-00-00-02" $(ppcmd)"/data/lzuhep/sw/Boss/dist/7.0.3/InstallArea/include/RelTable" $(ppcmd)"/data/lzuhep/sw/Boss/dist/7.0.3/BesCxxPolicy/BesCxxPolicy-00-01-01" $(ppcmd)"/data/lzuhep/sw/Boss//external/ROOT/5.34.09/x86_64-slc6-gcc46-opt/root/include" $(ppcmd)"/data/lzuhep/sw/Boss//external/Boost/1.50.0_python2.7/x86_64-slc6-gcc46-opt/include/boost-1_50" $(ppcmd)"$(BesFortranPolicy_root)/src" $(ppcmd)"$(BesCLHEP_root)/src" $(ppcmd)"/data/lzuhep/sw/Boss/external/CLHEP/Alist/Alist-00-00-06" $(ppcmd)"/data/lzuhep/sw/Boss/external/CLHEP/String/String-00-00-05" $(ppcmd)"/data/lzuhep/sw/Boss//external/clhep/2.0.4.5/x86_64-slc6-gcc46-opt/include" $(ppcmd)"/data/lzuhep/sw/Boss//external/HepMC/2.06.08/x86_64-slc6-gcc46-opt/include" $(ppcmd)"/data/lzuhep/sw/Boss//external/HepPDT/2.06.01/x86_64-slc6-gcc46-opt/include" $(ppcmd)"$(LCG_Platforms_root)/src" $(ppcmd)"$(BesExternalArea_root)/src" 
use_fincludes= $(use_includes)
use_stamps=  $(McDecayModeSvc_stamps)  $(McTruth_stamps)  $(EventModel_stamps)  $(Identifier_stamps)  $(RelTable_stamps)  $(BesPolicy_stamps)  $(BesCxxPolicy_stamps)  $(GaudiInterface_stamps)  $(GaudiSvc_stamps)  $(GaudiKernel_stamps)  $(GaudiPolicy_stamps)  $(Reflex_stamps)  $(Boost_stamps)  $(BesFortranPolicy_stamps)  $(BesCLHEP_stamps)  $(CLHEP_stamps)  $(HepMC_stamps)  $(HepPDT_stamps)  $(LCG_Settings_stamps)  $(LCG_Configuration_stamps)  $(LCG_Platforms_stamps)  $(BesExternalArea_stamps) 
use_cflags=  $(McDecayModeSvc_cflags)  $(McTruth_cflags)  $(EventModel_cflags)  $(Identifier_cflags)  $(RelTable_cflags)  $(BesPolicy_cflags)  $(BesCxxPolicy_cflags)  $(GaudiInterface_cflags)  $(GaudiSvc_cflags)  $(GaudiKernel_cflags)  $(GaudiPolicy_cflags)  $(Reflex_cflags)  $(Boost_cflags)  $(BesFortranPolicy_cflags)  $(BesCLHEP_cflags)  $(CLHEP_cflags)  $(HepMC_cflags)  $(HepPDT_cflags)  $(LCG_Settings_cflags)  $(LCG_Configuration_cflags)  $(LCG_Platforms_cflags)  $(BesExternalArea_cflags) 
use_pp_cflags=  $(McDecayModeSvc_pp_cflags)  $(McTruth_pp_cflags)  $(EventModel_pp_cflags)  $(Identifier_pp_cflags)  $(RelTable_pp_cflags)  $(BesPolicy_pp_cflags)  $(BesCxxPolicy_pp_cflags)  $(GaudiInterface_pp_cflags)  $(GaudiSvc_pp_cflags)  $(GaudiKernel_pp_cflags)  $(GaudiPolicy_pp_cflags)  $(Reflex_pp_cflags)  $(Boost_pp_cflags)  $(BesFortranPolicy_pp_cflags)  $(BesCLHEP_pp_cflags)  $(CLHEP_pp_cflags)  $(HepMC_pp_cflags)  $(HepPDT_pp_cflags)  $(LCG_Settings_pp_cflags)  $(LCG_Configuration_pp_cflags)  $(LCG_Platforms_pp_cflags)  $(BesExternalArea_pp_cflags) 
use_cppflags=  $(McDecayModeSvc_cppflags)  $(McTruth_cppflags)  $(EventModel_cppflags)  $(Identifier_cppflags)  $(RelTable_cppflags)  $(BesPolicy_cppflags)  $(BesCxxPolicy_cppflags)  $(GaudiInterface_cppflags)  $(GaudiSvc_cppflags)  $(GaudiKernel_cppflags)  $(GaudiPolicy_cppflags)  $(Reflex_cppflags)  $(Boost_cppflags)  $(BesFortranPolicy_cppflags)  $(BesCLHEP_cppflags)  $(CLHEP_cppflags)  $(HepMC_cppflags)  $(HepPDT_cppflags)  $(LCG_Settings_cppflags)  $(LCG_Configuration_cppflags)  $(LCG_Platforms_cppflags)  $(BesExternalArea_cppflags) 
use_pp_cppflags=  $(McDecayModeSvc_pp_cppflags)  $(McTruth_pp_cppflags)  $(EventModel_pp_cppflags)  $(Identifier_pp_cppflags)  $(RelTable_pp_cppflags)  $(BesPolicy_pp_cppflags)  $(BesCxxPolicy_pp_cppflags)  $(GaudiInterface_pp_cppflags)  $(GaudiSvc_pp_cppflags)  $(GaudiKernel_pp_cppflags)  $(GaudiPolicy_pp_cppflags)  $(Reflex_pp_cppflags)  $(Boost_pp_cppflags)  $(BesFortranPolicy_pp_cppflags)  $(BesCLHEP_pp_cppflags)  $(CLHEP_pp_cppflags)  $(HepMC_pp_cppflags)  $(HepPDT_pp_cppflags)  $(LCG_Settings_pp_cppflags)  $(LCG_Configuration_pp_cppflags)  $(LCG_Platforms_pp_cppflags)  $(BesExternalArea_pp_cppflags) 
use_fflags=  $(McDecayModeSvc_fflags)  $(McTruth_fflags)  $(EventModel_fflags)  $(Identifier_fflags)  $(RelTable_fflags)  $(BesPolicy_fflags)  $(BesCxxPolicy_fflags)  $(GaudiInterface_fflags)  $(GaudiSvc_fflags)  $(GaudiKernel_fflags)  $(GaudiPolicy_fflags)  $(Reflex_fflags)  $(Boost_fflags)  $(BesFortranPolicy_fflags)  $(BesCLHEP_fflags)  $(CLHEP_fflags)  $(HepMC_fflags)  $(HepPDT_fflags)  $(LCG_Settings_fflags)  $(LCG_Configuration_fflags)  $(LCG_Platforms_fflags)  $(BesExternalArea_fflags) 
use_pp_fflags=  $(McDecayModeSvc_pp_fflags)  $(McTruth_pp_fflags)  $(EventModel_pp_fflags)  $(Identifier_pp_fflags)  $(RelTable_pp_fflags)  $(BesPolicy_pp_fflags)  $(BesCxxPolicy_pp_fflags)  $(GaudiInterface_pp_fflags)  $(GaudiSvc_pp_fflags)  $(GaudiKernel_pp_fflags)  $(GaudiPolicy_pp_fflags)  $(Reflex_pp_fflags)  $(Boost_pp_fflags)  $(BesFortranPolicy_pp_fflags)  $(BesCLHEP_pp_fflags)  $(CLHEP_pp_fflags)  $(HepMC_pp_fflags)  $(HepPDT_pp_fflags)  $(LCG_Settings_pp_fflags)  $(LCG_Configuration_pp_fflags)  $(LCG_Platforms_pp_fflags)  $(BesExternalArea_pp_fflags) 
use_libraries= $(McTruth_libraries)  $(EventModel_libraries)  $(Identifier_libraries)  $(RelTable_libraries)  $(BesPolicy_libraries)  $(BesCxxPolicy_libraries)  $(GaudiInterface_libraries)  $(GaudiSvc_libraries)  $(GaudiKernel_libraries)  $(GaudiPolicy_libraries)  $(Reflex_libraries)  $(ROOT_libraries)  $(Boost_libraries)  $(Python_libraries)  $(tcmalloc_libraries)  $(libunwind_libraries)  $(BesFortranPolicy_libraries)  $(GCCXML_libraries)  $(xrootd_libraries)  $(BesCLHEP_libraries)  $(CLHEP_libraries)  $(HepMC_libraries)  $(HepPDT_libraries)  $(LCG_Settings_libraries)  $(LCG_Configuration_libraries)  $(LCG_Platforms_libraries)  $(BesExternalArea_libraries) 
McDecayModeSvcLib_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
McDecayModeSvcLib_use_linkopts=  $(McDecayModeSvc_linkopts)  $(McTruth_linkopts)  $(EventModel_linkopts)  $(Identifier_linkopts)  $(RelTable_linkopts)  $(BesPolicy_linkopts)  $(BesCxxPolicy_linkopts)  $(GaudiInterface_linkopts)  $(GaudiSvc_linkopts)  $(GaudiKernel_linkopts)  $(GaudiPolicy_linkopts)  $(Reflex_linkopts)  $(Boost_linkopts)  $(BesFortranPolicy_linkopts)  $(BesCLHEP_linkopts)  $(CLHEP_linkopts)  $(HepMC_linkopts)  $(HepPDT_linkopts)  $(LCG_Settings_linkopts)  $(LCG_Configuration_linkopts)  $(LCG_Platforms_linkopts)  $(BesExternalArea_linkopts) 
McDecayModeSvc_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
McDecayModeSvc_use_linkopts=  $(McDecayModeSvc_linkopts)  $(McTruth_linkopts)  $(EventModel_linkopts)  $(Identifier_linkopts)  $(RelTable_linkopts)  $(BesPolicy_linkopts)  $(BesCxxPolicy_linkopts)  $(GaudiInterface_linkopts)  $(GaudiSvc_linkopts)  $(GaudiKernel_linkopts)  $(GaudiPolicy_linkopts)  $(Reflex_linkopts)  $(Boost_linkopts)  $(BesFortranPolicy_linkopts)  $(BesCLHEP_linkopts)  $(CLHEP_linkopts)  $(HepMC_linkopts)  $(HepPDT_linkopts)  $(LCG_Settings_linkopts)  $(LCG_Configuration_linkopts)  $(LCG_Platforms_linkopts)  $(BesExternalArea_linkopts) 
config_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
install_includes_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
make_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
CompilePython_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
qmtest_run_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
qmtest_summarize_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
TestPackage_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
TestProject_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
new_rootsys_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
all_constituents= $(constituents)
constituentsclean= install_includesclean configclean McDecayModeSvcclean McDecayModeSvcLibclean 
all_constituentsclean= $(constituentsclean)
